version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: wyliebrown
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: interview_bot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
