version: '3.8'

services:
  auth-service:
    image: wyliebrown1990/auth-service
    command: gunicorn -b 0.0.0.0:5010 app:app
    ports:
      - "5001:5010"
    env_file:
      - .env
    depends_on:
      - postgres

  interview-service:
    image: wyliebrown1990/interview-service
    command: gunicorn -b 0.0.0.0:5013 app:app
    ports:
      - "5002:5013"
    env_file:
      - .env
    depends_on:
      - postgres

  training-data-service:
    image: wyliebrown1990/training-data-service
    command: gunicorn -b 0.0.0.0:5011 app:app
    ports:
      - "5011:5011"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
